---
# tasks file for httpd-amzlinux
- name: Install Apache Package
  ansible.builtin.package:
    name: httpd
    state: present

- name: Copy index.html file
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/index.html
  notify:
    - Restart httpd
  tags:
    - deploy

- name: Start service httpd, if not started
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes

